name: Release Build
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
env:
  Registry: https://api.nuget.org/v3/index.json
jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      working-directory: ./src
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      working-directory: ./src 
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      working-directory: ./src
    - name: Push
      run: dotnet nuget push ThorstenHans.JsonPatch.Contrib.${VERSION}.nupkg --source ${Registry} --api-key ${TOKEN}
      working-directory: ./src
      env:
        TOKEN: ${{ secrets.NUGET_API_TOKEN }}
